const FETCH_SUCCESS = 'Cases/Actions/COVID_STATS_FETCHED';
const FILTER_BY_COUNTRY_NAME = 'Cases/Actions/FILTER_BY_COUNTRY_NAME';
const FILTER_BY_PAGE_NUMBER = 'Cases/Actions/FILTER_BY_PAGE_NUMBER';
const CLEAR_COUNTRIES_PER_PAGE = 'Cases/Actions/CLEAR_COUNTRIES_PER_PAGE';
const FETCH_FAIL = 'Cases/Actions/COVID_STATS_FETCHE_FAIL';

export { FETCH_SUCCESS, FILTER_BY_COUNTRY_NAME, FILTER_BY_PAGE_NUMBER, CLEAR_COUNTRIES_PER_PAGE, FETCH_FAIL};